Add check for declared optreset
MUSL actually declare optreset and this cause compilation error:
librtpp_main.c:44:12: error: static declaration of 'optreset' follows non-static declaration
   44 | static int optreset; /* Not present in linux */
      |            ^~~~~~~~

Better handle this by scanning a declared optreset in configure.ac and
depend on the HAVE_DECL_OPTRESET macro to statically declare it instead
of extern reference it.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>