Add missing pthread.h in rtpp_proc_async
Fix compilation error for missing pthread_t type name.

rtpp_proc_async.h:44:34: error: unknown type name 'pthread_t'
   44 | void rtpp_proc_async_setprocname(pthread_t thread_id, const char *pname);
      |                                  ^~~~~~~~~

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>