src/rtpp_log_stand.c: fix format security error
Build breaks when compiling with "-Werror=format-security". Fix this by
adding the missing format specifier.

rtpp_log_stand.c' || echo './'`rtpp_log_stand.c
rtpp_log_stand.c: In function '_rtpp_log_write_va':
rtpp_log_stand.c:251:5: error: format not a string literal and no format arguments [-Werror=format-security]
     fprintf(stderr, rli->format_se[1]);
     ^~~~~~~
cc1: some warnings being treated as errors
make[5]: *** [Makefile:3252: rtpproxy-rtpp_log_stand.o] Error 1

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>