Link in libatomic if needed
When compiling for targets that need libatomic the build breaks:

/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: libucl_test-rtpp_memdeb.o: in function `rtpp_memdeb_malloc':
/home/sk/tmp/openwrt/build_dir/target-mips_24kc_musl/rtpproxy-2019-07-09-e6f1cf95/libucl/../src/rtpp_memdeb.c:273: undefined reference to `__atomic_fetch_add_8'
/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: /home/sk/tmp/openwrt/build_dir/target-mips_24kc_musl/rtpproxy-2019-07-09-e6f1cf95/libucl/../src/rtpp_memdeb.c:273: undefined reference to `__atomic_fetch_add_8'
/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: libucl_test-rtpp_memdeb.o: in function `rtpp_memdeb_realloc':
/home/sk/tmp/openwrt/build_dir/target-mips_24kc_musl/rtpproxy-2019-07-09-e6f1cf95/libucl/../src/rtpp_memdeb.c:379: undefined reference to `__atomic_fetch_add_8'
/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: /home/sk/tmp/openwrt/build_dir/target-mips_24kc_musl/rtpproxy-2019-07-09-e6f1cf95/libucl/../src/rtpp_memdeb.c:379: undefined reference to `__atomic_fetch_add_8'
/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: libucl_test-rtpp_memdeb.o: in function `rtpp_memdeb_strdup':
/home/sk/tmp/openwrt/build_dir/target-mips_24kc_musl/rtpproxy-2019-07-09-e6f1cf95/libucl/../src/rtpp_memdeb.c:431: undefined reference to `__atomic_fetch_add_8'
/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: libucl_test-rtpp_memdeb.o:/home/sk/tmp/openwrt/build_dir/target-mips_24kc_musl/rtpproxy-2019-07-09-e6f1cf95/libucl/../src/rtpp_memdeb.c:431: more undefined references to `__atomic_fetch_add_8' follow
/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: libucl_test-rtpp_memdeb_glitch.o: in function `rtpp_memdeb_glitch_init':
/home/sk/tmp/openwrt/build_dir/target-mips_24kc_musl/rtpproxy-2019-07-09-e6f1cf95/libucl/../src/rtpp_memdeb_glitch.c:110: undefined reference to `__atomic_store_8'
/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: /home/sk/tmp/openwrt/build_dir/target-mips_24kc_musl/rtpproxy-2019-07-09-e6f1cf95/libucl/../src/rtpp_memdeb_glitch.c:111: undefined reference to `__atomic_store_8'
/home/sk/tmp/openwrt/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/lib/gcc/mips-openwrt-linux-musl/7.4.0/../../../../mips-openwrt-linux-musl/bin/ld: /home/sk/tmp/openwrt/build_dir/target-mips_24kc_musl/rtpproxy-2019-07-09-e6f1cf95/libucl/../src/rtpp_memdeb_glitch.c:162: undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:449: libucl_test] Error 1

Fix this by adding a detection mechanism to configure.ac that links in
libatomic if needed. It's OK to check this unconditionally because
rtpproxy requires __atomic builtins always (see GLITCH_INJECT1() in
src/rtpp_memdeb_glitch.h).

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>